site_name: "Project Documentation"

nav:
  - Home: index.md
  - Application:
      - "Application Code": application.md
  - Infrastructure:
      - "Terraform Infrastructure": infra.md
  - Versioning:
      - "Version Policy": versioning.md

